### ISSUE TITLE
Removing Component Files Cumbersome

### ISSUE THREAD

**Issue by jhletendre** [SynBioHub/synbiohub#501] opened 2017-10-11 15:17 UTC
For some reason when I remove a component file, it reappears as a sequence file I have to again remove to permanently remove the file. I was wondering why this might be happening/if it is supposed to happen.

**Comment by cjmyers** [comment] 2018-01-10 16:27
Related to #502

**Comment by cjmyers** [comment] 2019-02-11 00:19
Duplicate of #650

**Closed by cjmyers** 2019-02-11 00:19 UTC
Labels: change
