### ISSUE TITLE
Collections truncated while viewing

### ISSUE THREAD

**Issue by PrashantVaidyanathan** [SynBioHub/synbiohub#627] opened 2018-05-18 01:41 UTC
The SBH collections seem to be truncated and only a specific subset of a collection is browsable. For instance, in one of the collections in [LCP Synbiohub](https://synbiohub.programmingbiology.org/) there are 50 objects in the collection however only 20 of them can be viewed as shown in the screenshot below. This seems to be the case for all collections. 

![sbhfiltererror](https://user-images.githubusercontent.com/2364721/40211803-b410280a-5a1a-11e8-9816-b8685646b734.png)

Ideally, all objects in an SBH collection should be viewable in the web interface.

**Comment by cjmyers** [comment] 2018-05-18 04:49
The list shows only those items that are not linked to any other items by default.  This allows the list to be more easy to navigate like a file tree.  For example, if you have Collection with a CD that includes another CD as a Component, you will be default only see the top-level CD, since you can navigate to the child CD via the top-level one.  Note that if the child CD is named "child" then if you start typing "child" in the search box that it will show up in the list.  I agree though that a button to "Show All" would be useful to add.

**Comment by cjmyers** [comment] 2018-05-29 14:43
Duplicate of #617

**Closed by cjmyers** 2018-05-29 14:43 UTC
Labels: change
