### ISSUE TITLE
Can't retrieve iGEM interlab parts

### ISSUE THREAD

**Issue by jakebeal** [SynBioHub/synbiohub#629] opened 2018-05-21 11:48 UTC
For the 2017 interlab parts http://parts.igem.org/Part:BBa_J364000, http://parts.igem.org/Part:BBa_J364001, and http://parts.igem.org/Part:BBa_J364002, I cannot obtain SBOL conversions.

Instead, I get sent to a SynBioHub error page, e.g.:

> Error: getType: https://synbiohub.org/public/igem/BBa_J364001 not found
    at sparql.queryJson.then (/home/deploy/synbiohub/lib/query/local/type.js:17:35)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by cjmyers** [comment] 2018-05-21 15:46
We still have had no update from Randy with 2017 parts. If you can give a gentle reminder maybe that would help.

Chris

**Comment by jakebeal** [comment] 2018-05-21 15:52
Before SynBioHub existed, conversions still worked.

On the assumption that lag between posting at iGEM and a data dump to SynBioHub will remain the norm rather than the exception, perhaps you could have this same functionality remain available as a backup for when SynBioHub doesn't have the requested part?

**Comment by cjmyers** [comment] 2018-05-21 15:57
It’s possible but here we also got stalled since there were issues with the registry XML API. The information provided is incomplete. Also there is no means to browse or search so you would need a part id to locate a part.

Chris

**Comment by udp** [comment] 2018-05-21 16:00
> Before SynBioHub existed, conversions still worked.

Actually, the conversion service was down for a long time before we pointed it at SynBioHub as a quick fix.

**Comment by cjmyers** [comment] 2018-05-22 22:06
Well, I actually did think quite a bit about this one awhile back.  I had an idea to create a view into the registry like we do with Benchling, but I got stalled on this due to the fact that there is no way that I'm aware of to get a list of all parts.  Therefore, I could not create a Collection view of the part list.  

We could potentially hardcode in something special for igem where it took any displayId in the igem collection and first checked if it existed in the registry, and if not, it rendered a page using the XML API from iGEM, though it would be somewhat incomplete.  This would likely not be too bad, but it would break precedent.  We have a clear distinction now between Collections stored in Virtuoso and those which are being rendered from remote sources (i.e., Benchling and ICE).  This would blur that distinction which is not ideal, but it might be necessary given the slow pace of getting updates from iGEM.  

I think we ended up deciding that a once a year update from iGEM should be mostly sufficient, since parts may be changing a lot during the year, and we would not want to have parts changing substantively once published.  I will re-ping Randy for the update, and we can reconsider a real-time SBOL conversion, if we think it is useful.

**Comment by jakebeal** [comment] 2018-05-23 03:26
Couldn't this be done not with a special case wouldn't be in SynBioHub but a special case in iGEM?

**Comment by cjmyers** [comment] 2018-05-23 21:53
I’m not sure this would be very easy.  James basically setup a forward from the iGEM website to synbiohub.org <http://synbiohub.org/> that twiddles the URL to lookup the part.  We would need a more sophisticated script that would first ping synbiohub.org <http://synbiohub.org/> to see if the part exists and if so go to the page, and if not then to run an SBOL converter.  We would also need to write this SBOL converter presumably it would be a conversion from the iGEM XML API to SBOL.  

I’m not sure that I’m really comfortable with this approach.  The problem is URIs.  What URIs would we give these parts?  Also, there would be no guarantee of these URIs being assigned to parts that are stable.  

The ideal scenario would be to implement the converter directly in the iGEM infrastructure, but that might not happen anytime soon.

**Comment by cjmyers** [comment] 2024-12-24 01:54
Cannot sort given current state of the iGEM registry

**Closed by cjmyers** 2024-12-24 01:54 UTC
Labels: question
