### ISSUE TITLE
Hand ("click me") cursor should not be shown for sequence features that aren't clickable

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#402] opened 2017-07-17 13:35 UTC

**Comment by cjmyers** [comment] 2017-07-17 13:40
This one should be moved to VisBol tracker.

**Comment by udp** [comment] 2017-07-17 13:44
no, the cursor is set by sbh's javascript, not visbol

**Comment by cjmyers** [comment] 2017-07-18 23:40
Hmm, I cannot reproduce this.  I only see the hand for clickable parts.  Do you have an example which is getting hand but not clickable?

**Comment by zachzundel** [comment] 2017-07-21 04:26
@udp could you give us steps to reproduce this? I'm not sure what it is either.

**Comment by zachzundel** [comment] 2017-07-26 00:44
Moving to 1.1.0 until we get more information.

**Comment by cjmyers** [comment] 2018-01-09 18:31
Can't reproduce closing.

**Closed by cjmyers** 2018-01-09 18:31 UTC
Labels: change
