### ISSUE TITLE
Unable To Upload Two SBOL Files That Contain The Same Parts

### ISSUE THREAD

**Issue by ckmadsen** [SynBioHub/synbiohub#566] opened 2018-01-22 22:18 UTC
I have two SBOL files that I would like to upload to the same collection.  The SBOL files contain some of the same parts, so I select the "Overwrite" option when I upload the second file to the same collection.  However, once I upload the second file, I receive this error when I try to download the SBOL or make the collection public:

Error: sbol-10202: The identity property of an Identified object MUST be globally unique. Reference: SBOL Version 2.1.0 Section 7.4 on page 17

I have attached the SBOL files causing this problem to this issue.

[sbol.zip](https://github.com/SynBioHub/synbiohub/files/1653762/sbol.zip)

**Comment by cjmyers** [comment] 2018-01-23 04:05
This works fine for me.  Are you sure you used the “Submit to Existing Collection” option?  Or are you doing this programmatically?  If programmatically, latest snapshot in libSBOLj has a createCollection method and an addToCollection method.

**Comment by ckmadsen** [comment] 2018-01-23 22:48
It's still not working for me.  I'm submitting to an existing collection through the web interface and have tried both with and without the "Overwrite" option.

**Comment by cjmyers** [comment] 2018-01-23 22:52
Can you send me a share link to your existing collection?  

Also, can you send me a screenshot of the error message?

I added the files *000.xml then *001.xml.  Did you do the same?

**Comment by ckmadsen** [comment] 2018-01-23 23:07
Sure.  Here's the link:

https://synbiohub.cidarlab.org/user/ckmadsen/Parts/Parts_collection/1/e8dc9c1df39866764f18e26073558c2e18cd6fbf/share

And the screenshot:

![screenshot](https://user-images.githubusercontent.com/6706620/35305679-35869750-0068-11e8-9c9f-3765573cc107.png)

And, yes.  I uploaded those same two files in that order.

**Comment by cjmyers** [comment] 2018-01-23 23:37
Ok, this is very strange.  When I upload P000, I have 48 parts (3 top level ones shown)

https://synbiohub.cidarlab.org/user/myers/P000/P000_collection/1/626cc7dd036914edd4c9835c03c17a65d9be295a/share <https://synbiohub.cidarlab.org/user/myers/P000/P000_collection/1/626cc7dd036914edd4c9835c03c17a65d9be295a/share>

When I upload P000 followed by P001, I have 96 parts (6 top level ones shown)

https://synbiohub.cidarlab.org/user/myers/P000_P001/P000_P001_collection/1/209d7ba074d1b1ff2eed74305b6385b68f447b07/share <https://synbiohub.cidarlab.org/user/myers/P000_P001/P000_P001_collection/1/209d7ba074d1b1ff2eed74305b6385b68f447b07/share>

When I open your share link, I see a collection that matches my collection with all 96 parts included, so it appears you have uploaded both already.  

I’m not sure I’m seeing your steps, maybe we can do a hangout and you can show me your steps.

**Comment by ckmadsen** [comment] 2018-01-23 23:44
When I try to download the SBOL of the collection on your second submission (the one with both P000 and P001), I get the same error that I get on my collection.  Does this not show up for you?

**Comment by cjmyers** [comment] 2018-01-23 23:45
Yes, now I have something to go on.  Let me check this one out.

**Comment by cjmyers** [comment] 2018-01-23 23:57
I see the problem.  The issue is that your objects have no “versions”, so the first upload stores all the parts as Version 1 to match the version for the collection you are creating, but your 2nd upload keeps the “no version”, so you get two copies.  One with a version and one without.  This is bad because you cannot have parts with a persistentIdentity match the identity of other parts.  Namely, you can mix both having versions and not.

Ironically, I was just discussing this issue with Michael.  I think we should change SynBioHub to rather than copy submission version number on creation of a collection and not on addition to a collection.  Instead, we should only update version of elements with NO version provided (i.e., files like yours).  

This will take a little bit to sort out this change, so is it possible for you to recreate your files with version of say “1” for each object and retry the create collection and add to collection?

**Comment by ckmadsen** [comment] 2018-01-24 00:12
Ah.  I see.  Yeah, we can regenerate these files with version numbers.  I'll let you know if we run into any issues once this is done.

**Comment by cjmyers** [comment] 2018-01-24 03:57
I’ve just checked in a fix for this issue and deployed it on cidarlab.  Let me know if you can now upload your two files even without versions.

**Comment by ckmadsen** [comment] 2018-01-26 00:01
Not sure if this is related, but I am unable to test this as the CIDAR Lab SynBioHub now times out whenever I try to download the SBOL for any of my collections or the public collections.  For instance, if I try to download the SBOL for the public Phoenix Features collection, the page says it's loading for a few minutes and then it ends up going to a "504 Gateway Time-out" page.  I then have to restart both virtuoso and SynBioHub in order to view submissions again.

The virtuoso tmux session prints out "No Web Server threads avalable, ServerThreads in [HTTP Server] may have to be increased" and the SynBioHub tmux session continually prints out jobs that it is receiving and servicing if that helps.

**Comment by cjmyers** [comment] 2018-01-26 00:04
Its possible that some recent commit to fix some issues may have added performance issues.  This was working before?  

How big are these collections?  Which collections in particular?

**Comment by ckmadsen** [comment] 2018-01-26 00:09
The public "Phoenix Features" collection has 59 entries.  The public "Rule 30" collection only has 3 entries but has the same problem.  Both of these collections have many more triples contained within their top level entries.

**Comment by ckmadsen** [comment] 2018-01-26 00:44
Okay.  Actually, the fix you made did fix the issue.  I am now able to upload the two SBOL files to the same collection and retrieve the SBOL for the combined collection.  However, the other collections still time out if I try to download their SBOL.

**Comment by cjmyers** [comment] 2018-01-26 01:13
Ok will check. Maybe an infinite loop somewhere 

Chris

**Comment by cjmyers** [comment] 2018-01-26 02:29
Yes, it is an infinite loop.  I see the problem.  It is trying to fetch all objects, it has an annotation that points to itself, so it keeps fetching itself over and over again.  I’ve made a temporary fix to remove cidarlab from web-of-registries, but this is not ideal.  Will get it sorted.  Thanks for finding this.

**Comment by cjmyers** [comment] 2018-01-26 02:34
Ok, I found it.  Was a recent addition.  Please check.  Should be fixed now.

**Comment by ckmadsen** [comment] 2018-01-26 05:50
This seems to be fixed now.  Thanks!

**Closed** 2018-01-26 19:27 UTC
