### ISSUE TITLE
SynBioHub should return an error when trying to upload a duplicate

### ISSUE THREAD

**Issue by chrisAta** [SynBioHub/synbiohub#575] opened 2018-02-06 09:51 UTC
At the moment, if you try to upload a file that already exists in a SynBioHub instance i.e. a duplicate, the submission goes through showing just an empty table. 

In the case of a full duplicate where everything gets trimmed out, it should probably give you some error statement to let the user know.

**Comment by jakebeal** [comment] 2019-02-01 12:12
I want to bump the priority of this one.  I just got burned by it as well.

**Comment by cjmyers** [comment] 2019-07-09 09:42
Duplicate of #916 which is more detailed, so closing this one.

**Closed by cjmyers** 2019-07-09 09:42 UTC
Labels: Priority, change
