### ISSUE TITLE
submitted new parts to a collection not showing

### ISSUE THREAD

**Issue by geoffbaldwin** [SynBioHub/synbiohub#1007] opened 2019-09-20 10:24 UTC
When i submit existing parts to a collection they do not appear in the collection page as the view is filtered.
Is it possible to toggle the filtering?

**Comment by cjmyers** [comment] 2020-05-25 17:55
We have changed how we manage collections when you link in existing parts.  They should be showing up now, and you should have improved means to edit these collections of existing parts.  Ask me to demo for you some time @geoffbaldwin 

Agree that we need a check box for filtering, but this issue is a duplicate of #617

**Closed by cjmyers** 2020-05-25 17:55 UTC
Labels: change
