### ISSUE TITLE
ENOSPC ERROR when pushing data to a SynBioHub Instance

### ISSUE THREAD

**Issue by tramyn** [SynBioHub/synbiohub#606] opened 2018-04-05 18:59 UTC
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Successfully uploaded
Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)Successfully uploaded
Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)

Error: ENOSPC: no space left on device, write
    at Error (native)Successfully uploaded
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Successfully uploaded

Successfully uploaded
Successfully uploaded

Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)

Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)

Successfully uploaded
Successfully uploaded
Error: ENOSPC: no space left on device, write
    at Error (native)

Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)

Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)

Error: ENOSPC: no space left on device, write
    at Error (native)

Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)

Successfully uploaded
Successfully uploaded

Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)

Error: ENOSPC: no space left on device, write
    at Error (native)

Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Successfully uploaded
Error: java.lang.IllegalStateException: com.ctc.wstx.exc.WstxIOException: No space left on device
        at uk.ac.ncl.intbio.core.datatree.PropertyValue$Visitor.visit(PropertyValue.java:35)
        at uk.ac.ncl.intbio.core.io.rdf.RdfIo$1.write(RdfIo.java:112)
        at uk.ac.ncl.intbio.core.io.rdf.RdfIo$1.write(RdfIo.java:86)
        at uk.ac.ncl.intbio.core.io.rdf.RdfIo$1.write(RdfIo.java:68)
        at org.sbolstandard.core2.SBOLWriter.writeRDF(SBOLWriter.java:295)
        at org.sbolstandard.core2.SBOLWriter.write(SBOLWriter.java:164)
        at org.sbolstandard.core2.SBOLWriter.write(SBOLWriter.java:127)
        at org.synbiohub.PrepareSubmissionJob.execute(PrepareSubmissionJob.java:509)
        at org.synbiohub.Main$1.run(Main.java:30)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.ctc.wstx.exc.WstxIOException: No space left on device
        at com.ctc.wstx.sw.BaseNsStreamWriter.doWriteStartTag(BaseNsStreamWriter.java:621)
        at com.ctc.wstx.sw.SimpleNsStreamWriter.writeStartOrEmpty(SimpleNsStreamWriter.java:273)
        at com.ctc.wstx.sw.BaseNsStreamWriter.writeEmptyElement(BaseNsStreamWriter.java:273)
        at javanet.staxutils.IndentingXMLStreamWriter.writeEmptyElement(IndentingXMLStreamWriter.java:185)
        at uk.ac.ncl.intbio.core.io.rdf.RdfIo$1.writeEmptyElement(RdfIo.java:154)
        at uk.ac.ncl.intbio.core.io.rdf.RdfIo$1.access$300(RdfIo.java:46)
        at uk.ac.ncl.intbio.core.io.rdf.RdfIo$1$1.visit(RdfIo.java:104)
        at uk.ac.ncl.intbio.core.datatree.PropertyValue$Visitor.visit(PropertyValue.java:33)
        ... 13 more
Caused by: java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at com.ctc.wstx.sw.BufferingXmlWriter.flushBuffer(BufferingXmlWriter.java:1416)
        at com.ctc.wstx.sw.BufferingXmlWriter.fastWriteRaw(BufferingXmlWriter.java:1462)
        at com.ctc.wstx.sw.BufferingXmlWriter.writeStartTagStart(BufferingXmlWriter.java:792)
        at com.ctc.wstx.sw.BaseNsStreamWriter.doWriteStartTag(BaseNsStreamWriter.java:616)
        ... 20 more

    at responseCallbacks.(anonymous function) (/opt/synbiohub/lib/java.js:89:24)
    at DestroyableTransform.javaProcess.stdout.pipe.on (/opt/synbiohub/lib/java.js:51:5)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (/opt/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/opt/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (/opt/synbiohub/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (/opt/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at DestroyableTransform.write [as _transform] (/opt/synbiohub/node_modules/binary-split/index.js:24:14)
    at DestroyableTransform.Transform._read (/opt/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/opt/synbiohub/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/opt/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/opt/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/opt/synbiohub/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
Error: ENOSPC: no space left on device, write
    at Error (native)Successfully uploaded
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)

**Comment by tramyn** [comment] 2018-04-05 19:01
More errors.

Error: split_to_n3 returned exit code 1
    at ChildProcess.splitProcess.on (/opt/synbiohub/lib/sparql/sparql.js:360:28)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
Successfully uploaded
Error: ENOSPC: no space left on device, write
    at Error (native)Successfully uploaded
Successfully uploaded
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)Error: ENOSPC: no space left on device, write
    at Error (native)
Error: ENOSPC: no space left on device, write
    at Error (native)

**Comment by cjmyers** [comment] 2018-04-05 19:03
Looks like you are out of disk space.  Not sure what the limit is on space in a docker image.

Zach?

**Comment by zachzundel** [comment] 2018-04-05 20:25
I wonder if you're filling up `/tmp`, could you check it with `df`?

**Comment by udp** [comment] 2018-04-05 21:14
Or inodes?

**Comment by zachzundel** [comment] 2018-04-06 23:30
This is a duplicate of our old friend #334. I've chatted with @tramyn and resolved this particular manifestation of the issue.

**Closed by zachzundel** 2018-04-06 23:30 UTC
