### ISSUE TITLE
Fix serif fonts in random places

### ISSUE THREAD

**Issue by udp** [SynBioHub/synbiohub#176] opened 2017-02-25 01:56 UTC
Happens in firefox on Linux but I don't remember seeing it on OS X.  I guess we don't specify a default font for something.

**Comment by 16zzundel5** [comment] 2017-05-11 09:29
I found that this is usually caused by including a <p> tag _within_ a FontAwesome span. I'm going to close this bug since I can't see any more of these, and this is a little general to keep open. I'll open individual issues for specific ones.

**Closed by 16zzundel5** 2017-05-11 09:29 UTC
Labels: bug
